language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.20"
  - "5.30"
  - "5.32"
  - "blead"
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
